import { access, constants, mkdir, writeFile } from "node:fs/promises"
import path from "node:path"

import { contractChecks, expectedBaseline } from "./contract.mjs"
import { runProcess } from "./process.mjs"

export const GATE_WRAPPER = ".codegen-contract/gate.sh"
export const CHECKS_DIRECTORY = ".codegen-contract/checks"

export function checkScriptPath(checkId) {
  return `${CHECKS_DIRECTORY}/${checkId}.sh`
}

// One script per check. The Gate Designer may replace its body; the contract
// and the wrapper stay out of its reach.
export function checkScript(command) {
  return [
    "#!/usr/bin/env bash",
    "# Generated by the OpenCode codegen orchestrator from the contract's check.",
    "# The Gate Designer may rewrite this file; the contract and gate.sh are sealed.",
    "set -euo pipefail",
    command,
    "",
  ].join("\n")
}

// The Builder may only run `bash .codegen-contract/gate.sh`, so every contract
// gate is materialized as that wrapper around the contract's checks. It runs
// every check, prints one verdict line per check, and fails if any failed.
export function gateScript(checks) {
  return [
    "#!/usr/bin/env bash",
    "# Generated by the OpenCode codegen orchestrator. Do not edit.",
    "set -uo pipefail",
    "cd \"$(dirname \"${BASH_SOURCE[0]}\")/..\"",
    "status=0",
    "run_check() {",
    "  local id=\"$1\"",
    "  if bash \".codegen-contract/checks/${id}.sh\"; then",
    "    printf 'CHECK %s: PASS\\n' \"$id\"",
    "  else",
    "    printf 'CHECK %s: FAIL\\n' \"$id\"",
    "    status=1",
    "  fi",
    "}",
    ...checks.map((check) => `run_check ${JSON.stringify(check.id)}`),
    "if [ \"$status\" -eq 0 ]; then printf 'CONTRACT GATE: PASS\\n'; else printf 'CONTRACT GATE: FAIL\\n'; fi",
    "exit \"$status\"",
    "",
  ].join("\n")
}

// The sealed contract points every check at its script; the Planner's
// command is kept as source_command for the record.
export function sealContract(contract) {
  const checks = contractChecks(contract).map((check) => ({
    ...check,
    source_command: check.command,
    command: `bash ${checkScriptPath(check.id)}`,
  }))
  return { ...contract, verification: { ...contract.verification, checks } }
}

// Writes the check scripts and the wrapper into the worktree and returns the
// sealed contract. Used by the orchestrator, certification, and the tests.
export async function materializeGate(directory, contract) {
  const sealed = sealContract(contract)
  await mkdir(path.join(directory, CHECKS_DIRECTORY), { recursive: true })
  for (const check of sealed.verification.checks) {
    await writeFile(path.join(directory, checkScriptPath(check.id)), checkScript(check.source_command))
  }
  await writeFile(path.join(directory, GATE_WRAPPER), gateScript(sealed.verification.checks))
  return sealed
}

// Parses the verdict lines the wrapper prints.
export function parseGateOutput(output) {
  const results = []
  for (const line of String(output ?? "").split("\n")) {
    const match = line.match(/^CHECK (\S+): (PASS|FAIL)$/)
    if (match) results.push({ check_id: match[1], result: match[2] })
  }
  return results
}

function referencedScript(command) {
  const tokens = command.trim().split(/\s+/)
  for (const token of tokens.slice(0, 3)) {
    if (token.includes("/") || /\.(sh|py|mjs|js)$/.test(token)) return token
  }
  return null
}

async function executable(filePath) {
  try {
    await access(filePath, constants.R_OK)
    return true
  } catch {
    return false
  }
}

const FIXABLE = /^(no-verification-checks|missing-script:|check-passes-on-baseline:)/

// GATE_READY means the way to judge the result exists before anyone codes:
// every check resolves, and on the untouched baseline each check behaves as
// the requirements it covers demand (fails for a change, passes for
// preserved behavior). Reasons name the check, so the Gate Designer knows
// exactly which requirement lacks a real check. A preserve check that fails
// on the baseline is not the designer's to fix: the baseline is broken or
// the requirement is mislabeled.
export async function checkGateReadiness({
  directory,
  contract,
  timeoutSeconds = 300,
  run = runProcess,
}) {
  const reasons = []
  const checks = contractChecks(contract)
  if (checks.length === 0) {
    return { ready: false, fixable: true, reasons: ["no-verification-checks"], baseline: [] }
  }
  for (const check of checks) {
    const script = referencedScript(check.command ?? "")
    if (script && !script.startsWith("-") && !(await executable(path.resolve(directory, script)))) {
      reasons.push(`missing-script:${script}`)
    }
  }
  if (reasons.length > 0) return { ready: false, fixable: true, reasons, baseline: [] }

  const baseline = []
  for (const check of checks) {
    const expected = expectedBaseline(check, contract)
    const result = await run(check.command, [], { cwd: directory, timeoutSeconds, shell: true })
    baseline.push({
      check_id: check.id,
      command: check.command,
      covers: check.covers,
      expected,
      exit_code: result.exitCode,
    })
    if (expected === "fail" && result.exitCode === 0) reasons.push(`check-passes-on-baseline:${check.id}`)
    if (expected === "pass" && result.exitCode !== 0) reasons.push(`check-fails-on-baseline:${check.id}`)
  }
  const fixable = reasons.length > 0 && reasons.every((reason) => FIXABLE.test(reason))
  return { ready: reasons.length === 0, fixable, reasons, baseline }
}
